#!/bin/bash
# $Id: spamupdate,v 1.1 2018/07/01 08:38:46 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/spamupdate,v $
# $Revision: 1.1 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: spamupdate,v 1.1 2018/07/01 08:38:46 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.1 $ $Date: 2018/07/01 08:38:46 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done

config=${config:-/usr/local/etc/${cmd}.cf
[ -r $config ]||{echo $cmd: Can't find $config;exit 1}
eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`
ssh mailhost "cd mail
for f in spam? ;do
	[ -f $f.1 ] && mv $f.1 $f.2	
	cp $f $f.1
	> $f
	[ -f $f.2 ] && sa-learn --mbox --spam $f.2
done "


		
